name: elsie

services:
  database:
    image: postgres:15.5
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  database_data:
